### ISSUE TITLE
isScrollOut属性无效

### ISSUE THREAD

**Issue by HLHSDMZ** [lztbwlkj/MSLaunchView#1]
self.videoUrl = videoUrl;
        videoFrame = frame;
        guideFrame = gframe;
        gbgImage = gImage;
        isScrollOut = isScrollOut;
        
        self.isPalyEndOut = YES;
        self.videoGravity = AVLayerVideoGravityResizeAspectFill;
        ==============================================
这段代码中，isScrollOut是你传过来的局部属性，并不会对launchView的isScrollOut这个全局属性生效。要换个名字

**Comment by lztbwlkj** [comment]
感谢!!已修改,稍后可更新试试。
