### ISSUE TITLE
发现个问题，有时候点击立即体验获取不到点击事件

### ISSUE THREAD

**Issue by foermo4-hao** [lztbwlkj/MSLaunchView#2]
<img width="788" alt="image" src="https://user-images.githubusercontent.com/36944885/59079016-6813f380-8914-11e9-9100-880f15ce33b3.png">

**Comment by foermo4-hao** [comment]
新创建的imageView 的userInteractionEnabled属性不设置 会导致有时候立即体验按钮点击无效，建议不要判断直接加入

**Comment by lztbwlkj** [comment]
感谢！ 我会尽快更新！
